export const mockAfwezigheden = [
  {
    id: 1,
    werknemer: "Jonas Van Aert",
    werknemerId: 1,
    startDate: "Dec 22, 2025",
    endDate: "Dec 23, 2025",
    days: "2 dagen",
    type: "Vakantie",
    status: "In behandeling",
    reason: "Familieweekend in de Ardennen",
    canCancel: true,
  },
  {
    id: 2,
    werknemer: "Lisa Peeters",
    startDate: "Nov 10, 2025",
    endDate: "Nov 12, 2025",
    days: "3 dagen",
    type: "Ziekte",
    status: "Goedgekeurd",
    reason: "Zware griep en hoge koorts",
    canCancel: false,
  },
  {
    id: 3,
    werknemer: "Jonas Van Aert",
    werknemerId: 1,
    startDate: "Jan 05, 2026",
    endDate: "Jan 10, 2026",
    days: "5 dagen",
    type: "Vakantie",
    status: "Goedgekeurd",
    reason: "Skivakantie",
    canCancel: false,
  },
  {
    id: 4,
    werknemer: "Lisa Peeters",
    startDate: "Feb 01, 2026",
    endDate: "Feb 02, 2026",
    days: "2 dagen",
    type: "Vakantie",
    status: "Geweigerd",
    reason: "Verhuizing",
    canCancel: false,
  },
  {
    id: 5,
    werknemerId: 1,
    werknemer: "Jonas Van Aert",
    startDate: "Mar 15, 2026",
    endDate: "Jul 15, 2026",
    days: "4 maanden",
    type: "Ziekte",
    status: "Goedgekeurd",
    reason: "Langdurige ziekte na operatie",
    canCancel: true,
  }
];

export const mockStats = {
  totaleZiektedagen: 3,
  totaleVakantiedagen: 0,
};
